name: Terraform CI

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Check Terraform version
      - name: Terraform Version
        run: terraform version

      # Terraform initialization
      - name: Terraform Init
        run: terraform init -backend=false

      # Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Terraform validation
      - name: Terraform Validate
        run: terraform validate

      # Install TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      # Run TFLint
      - name: Run TFLint
        run: |
          tflint --init
          tflint --recursive

      # Terraform Security Scan
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: false

      # Secret Detection
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}